### ISSUE TITLE
Error:  `np.NaN` was removed in the NumPy 2.0 release.

### ISSUE THREAD

**Issue by Tasogarre** [juftin/lunchable-primelunch#6]
On a fresh install of Lunchable and PrimeLunch from a pipx install (fresh python and pipx install on Windows 11), I received the following error during initial execution:

```AttributeError: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.```

Modified row 86 of primelunch.py to `np.nan` from `np.NaN` and was able to execute PrimeLunch without issue.

**Comment by juftin** [comment]
Sorry for the delay!
